namespace Condor.Visitor.Generator
{
    internal static class DefaultTemplates
    {
        internal const string VisitorTemplate = @"// <auto-generated>
{{#*inline ""LowResponse""}}
{{~#if IsAsync}}{{~#if HasReturnType}}ValueTask<{{{ReturnType}}}>{{~else~}}ValueTask{{/if~}}{{else}}{{~#if HasReturnType}}{{{ReturnType}}}{{~else~}}void{{/if~}}{{/if~}}
{{/inline}}
{{#*inline ""Response""}}
{{~#if ../IsAsync}}{{~#if ../HasReturnType}}ValueTask<{{{../ReturnType}}}>{{~else~}}ValueTask{{/if~}}{{else}}{{~#if ../HasReturnType}}{{{../ReturnType}}}{{~else~}}void{{/if~}}{{/if~}}
{{/inline}}
{{#*inline ""ResponseNested""}}
{{~#if ../../IsAsync}}{{~#if ../../HasReturnType}}ValueTask<{{{../../ReturnType}}}>{{~else~}}ValueTask{{/if~}}{{else}}{{~#if ../../HasReturnType}}{{{ ../../ReturnType}}}{{~else~}}void{{/if~}}{{/if~}}
{{/inline}}
{{#*inline ""VisitOptionsClass""}}
    {{#each ImplementationGroup}}
        {{#if AddVisitFallBack}}
        public partial {{>Response}} {{../VisitMethodName}}FallBack({{{VisitedType.TypeFullName}}} element{{#each ../TypedArgs}}, {{{ParamTypeFullName}}} {{SanitizedParamName}}{{/each}});
        {{/if}}
        {{#if AddVisitRedirect}}
        public virtual {{>Response}} {{../VisitMethodName}}Redirect({{{VisitedType.TypeFullName}}} element{{#each ../TypedArgs}}, {{{ParamTypeFullName}}} {{SanitizedParamName}}{{/each}})
        {
            switch (element)
            {
                {{#each ImplementationTypes}}
                case {{{TypeFullName}}} x:
                    {{#if ../../HasReturnType}} 
                    return {{../../VisitMethodName}}(x{{#each ../../TypedArgs}}, {{SanitizedParamName}}{{/each}});
                    {{else}}
                    {{#if ../../IsAsync}}
                    return {{../../VisitMethodName}}(x{{#each ../../TypedArgs}}, {{SanitizedParamName}}{{/each}});
                    {{else}}
                    {{../../VisitMethodName}}(x{{#each ../../TypedArgs}}, {{SanitizedParamName}}{{/each}});
                    break;
                    {{/if}}
                    {{/if}}
                {{/each}}
                default:
                    {{#if AddVisitFallBack}}
                    {{#if ../../HasReturnType}} 
                    return {{../VisitMethodName}}FallBack(element{{#each ../TypedArgs}}, {{SanitizedParamName}}{{/each}});
                    {{else}}
                    {{#if ../../IsAsync}}
                    return {{../VisitMethodName}}FallBack(element{{#each ../TypedArgs}}, {{SanitizedParamName}}{{/each}});
                    {{else}}
                    {{../VisitMethodName}}FallBack(element{{#each ../TypedArgs}}, {{SanitizedParamName}}{{/each}});
                    break;
                    {{/if}}
                    {{/if}}
                    {{else}}
                    throw new System.NotSupportedException(""Unsupported type"");
                    {{/if}}
            }
        }
        {{/if}}
        {{#each ImplementationTypes}}
        public partial {{>ResponseNested}} {{../../VisitMethodName}}({{{TypeFullName}}} element{{#each ../../TypedArgs}}, {{{ParamTypeFullName}}} {{SanitizedParamName}}{{/each}});
        {{/each}}
    {{/each}}
{{/inline}}
{{#*inline ""VisitOptionsInterface""}}
    {{#each ImplementationGroup}}
        {{#if AddVisitFallBack}}
        {{>Response}} {{../VisitMethodName}}FallBack({{{VisitedType.TypeFullName}}} element{{#each ../TypedArgs}}, {{{ParamTypeFullName}}} {{SanitizedParamName}}{{/each}});
        {{/if}}
        {{#if AddVisitRedirect}}
        {{>Response}} {{../VisitMethodName}}Redirect({{{VisitedType.TypeFullName}}} element{{#each ../TypedArgs}}, {{{ParamTypeFullName}}} {{SanitizedParamName}}{{/each}});
        {{/if}}
        {{#each ImplementationTypes}}
        {{>ResponseNested}} {{../../VisitMethodName}}({{{TypeFullName}}} element{{#each ../../TypedArgs}}, {{{ParamTypeFullName}}} {{SanitizedParamName}}{{/each}}{{#each ../Args}}, {{{.}}}{{/each}});
        {{/each}}
    {{/each}}
{{/inline}}

namespace {{OutputNamespace}}
{
    {{AccessibilityModifier}} partial {{{KeywordTypeDefinition}}} {{{OriginalTypeDefinition}}}
    {
        {{#if IsInterface}}
        {{>VisitOptionsInterface}}
        {{else}}
        {{>VisitOptionsClass}}
        {{/if}}
    }
    {{#if Visitable.GenerateVisitable}}
    {{AccessibilityModifier}} partial interface {{{Visitable.VisitableTypeName}}} {
        {{>LowResponse}} {{Visitable.AcceptMethodName}}{{{GenericTypesDefinition}}}({{BaseTypeDefinition}}{{{GenericTypesDefinition}}} visitor{{#each Visitable.VisitableParameters}}, {{{ParamTypeFullName}}} {{SanitizedParamName}}{{/each}});
    }
    {{/if}}
    {{#if Default.GenerateDefault}}
    {{#if Default.ForcePublic}}public {{else}}{{AccessibilityModifier}} {{/if}}{{#if Default.IsAbstract}}abstract {{/if}}{{#if Default.IsPartial}}partial {{/if}}class Default{{Default.DefaultTypeName}}{{{GenericTypesDefinition}}} : {{BaseTypeDefinition}}{{{GenericTypesDefinition}}}
    {
        {{#each ImplementationGroup}}
        {{#if AddVisitFallBack}}
        {{#if ../Default.IsAbstract}}
        public abstract {{>Response}} {{../VisitMethodName}}FallBack({{{VisitedType.TypeFullName}}} element{{#each ../TypedArgs}}, {{{ParamTypeFullName}}} {{SanitizedParamName}}{{/each}});
        {{else}}
        {{#if ../Default.IsPartial}}
        public partial {{>Response}} {{../VisitMethodName}}FallBack({{{VisitedType.TypeFullName}}} element{{#each ../TypedArgs}}, {{{ParamTypeFullName}}} {{SanitizedParamName}}{{/each}});
        {{else}}
        public virtual {{>Response}} {{../VisitMethodName}}FallBack({{{VisitedType.TypeFullName}}} element{{#each ../TypedArgs}}, {{{ParamTypeFullName}}} {{SanitizedParamName}}{{/each}})
        {
            throw new System.NotImplementedException();
        }
        {{/if}}
        {{/if}}
        {{/if}}
        {{#if AddVisitRedirect}}
        public virtual {{>Response}} {{../VisitMethodName}}Redirect({{{VisitedType.TypeFullName}}} element{{#each ../TypedArgs}}, {{{ParamTypeFullName}}} {{SanitizedParamName}}{{/each}})
        {
            switch (element)
            {
                {{#each ImplementationTypes}}
                case {{{TypeFullName}}} x:
                    {{#if ../../HasReturnType}} 
                    return {{../../VisitMethodName}}(x{{#each ../../TypedArgs}}, {{SanitizedParamName}}{{/each}});
                    {{else}}
                    {{#if ../../IsAsync}}
                    return {{../../VisitMethodName}}(x{{#each ../../TypedArgs}}, {{SanitizedParamName}}{{/each}});
                    {{else}}
                    {{../../VisitMethodName}}(x{{#each ../../TypedArgs}}, {{SanitizedParamName}}{{/each}});
                    break;
                    {{/if}}
                    {{/if}}
                {{/each}}
                default:
                    {{#if AddVisitFallBack}}
                    {{#if ../HasReturnType}}
                    return {{../VisitMethodName}}FallBack(element{{#each ../TypedArgs}}, {{SanitizedParamName}}{{/each}});
                    {{else}}
                    {{#if ../IsAsync}}
                    return {{../VisitMethodName}}FallBack(element{{#each ../TypedArgs}}, {{SanitizedParamName}}{{/each}});
                    {{else}}
                    {{../VisitMethodName}}FallBack(element{{#each ../TypedArgs}}, {{SanitizedParamName}}{{/each}});
                    break;
                    {{/if}}
                    {{/if}}
                    {{else}}
                    throw new System.NotSupportedException();
                    {{/if}}
            }
        }
        {{/if}}
        {{#each ImplementationTypes}}
        {{#if ../../Default.IsVisitAbstract}}
        public abstract {{>ResponseNested}} {{../../VisitMethodName}}({{{TypeFullName}}} element{{#each ../../TypedArgs}}, {{{ParamTypeFullName}}} {{SanitizedParamName}}{{/each}});
        {{else}}        
        public virtual {{>ResponseNested}} {{../../VisitMethodName}}({{{TypeFullName}}} element{{#each ../../TypedArgs}}, {{{ParamTypeFullName}}} {{SanitizedParamName}}{{/each}})
        {
            {{#if ../../HasReturnType}}   
            {{#if ../AddVisitFallback}}
            return {{../../VisitMethodName}}FallBack(element{{#each ../../TypedArgs}}, {{SanitizedParamName}}{{/each}});
            {{else}}
            return default!;
            {{/if}}
            {{else}}
            {{#if ../AddVisitFallback}}
            {{../../VisitMethodName}}FallBack(element{{#each ../../TypedArgs}}, {{SanitizedParamName}}{{/each}});
            {{else}}
            return;
            {{/if}}
            {{/if}}
        }
        {{/if}}
    {{/each}}
    {{/each}}
    }
    {{/if}}
}";
    }
}
