# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x
        source-url: https://nuget.pkg.github.com/junglistkirss/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal

    - name: NuGet
      run: dotnet pack --no-build --configuration Release -o .

    - name: Push to GitHub package registry
      run: dotnet nuget push *.nupkg --api-key "${{ secrets.NUGET_TOKEN }}" --source https://nuget.pkg.github.com/junglistkirss/index.json --skip-duplicate
